"use client"; // This is necessary to ensure you are using the client-side version of React, box-ui-elements does not support SSR
import localFont from "next/font/local";
import "./globals.css";
import styles from "./page.module.css";
import { IntlProvider } from "react-intl";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// IntlProvider is necessary to provide the correct locale for the components
// locale and messages are required, you can use the messages from box-ui-elements or create your own
// by default all messages are in english, changing locale does not change the messages alone

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <ul className={styles.tabHeader}>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/annotations">Annotations</a>
            </li>
          </ul>
        </nav>
        <IntlProvider locale="en">
          <main className={styles.main}>{children}</main>
        </IntlProvider>
      </body>
    </html>
  );
}
